"""Checks on the MiniMappr front end.

There is no JavaScript engine in this project, so these do not run the app.
What they do cover is the contract that is easiest to break by hand: a
legend setting is declared once in ``LEGEND_CONTROLS`` and has to line up
with a control in the markup, with the code that reads it, and with the
generated ``index.html``. A mismatch there is silent in the browser - the
control simply does nothing - so it is worth catching here.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
APP = ROOT / "minimappr" / "app"
BODY = ROOT / "minimappr" / "body.html"
STATE = APP / "30-styles-state.js"
INDEX = ROOT / "index.html"

_JS_LITERALS = {"true": True, "false": False, "null": None}


def _literal(text: str):
    text = text.strip()
    if text in _JS_LITERALS:
        return _JS_LITERALS[text]
    if text.startswith('"'):
        return text.strip('"')
    return float(text)


@pytest.fixture(scope="module")
def controls():
    """The LEGEND_CONTROLS table as [(id, kind, default), ...]."""
    source = STATE.read_text(encoding="utf-8")
    table = re.search(r"const LEGEND_CONTROLS = \[(.*?)\n\];", source, re.S)
    assert table, "LEGEND_CONTROLS table not found"
    rows = [(name, kind, _literal(default)) for name, kind, default in
            re.findall(r'\["(\w+)",\s*"(\w+)",\s*(.+?)\],', table.group(1))]
    assert rows, "LEGEND_CONTROLS parsed empty"
    return rows


@pytest.fixture(scope="module")
def body():
    return BODY.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def app_js():
    return "".join(p.read_text(encoding="utf-8")
                   for p in sorted(APP.glob("*.js")))


def _markup_default(body: str, element_id: str):
    """A control's default straight out of the markup."""
    select = re.search(r'<select[^>]*id="%s".*?</select>' % element_id,
                       body, re.S)
    if select:
        option = re.search(r'<option value="([^"]*)"', select.group(0))
        return option.group(1) if option else None
    tag = re.search(r'<input[^>]*id="%s"[^>]*>' % element_id, body)
    if not tag:
        return None
    if 'type="checkbox"' in tag.group(0):
        return "checked" in tag.group(0)
    value = re.search(r'value="([^"]*)"', tag.group(0))
    return value.group(1) if value else ""


def test_every_declared_control_exists_in_the_markup(controls, body):
    declared = {name for name, _kind, _default in controls}
    in_markup = set(re.findall(r'id="(leg\w+)"', body))
    assert declared - in_markup == set(), "declared but no control on the page"
    assert in_markup - declared == set(), "control on the page but undeclared"


def test_no_option_is_read_without_being_declared(controls, app_js):
    declared = {name for name, _kind, _default in controls}
    read = set(re.findall(r"opts\.(leg\w+)", app_js))
    assert read - declared == set(), "read from opts but never declared"


def test_no_option_is_declared_without_being_used(controls, app_js):
    # A declared-but-unread setting is a control that visibly does nothing.
    declared = {name for name, _kind, _default in controls}
    read = set(re.findall(r"opts\.(leg\w+)", app_js))
    assert declared - read == set(), "declared but nothing reads it"


def test_markup_defaults_match_the_table(controls, body):
    mismatched = {}
    for name, kind, default in controls:
        found = _markup_default(body, name)
        if kind == "bool":
            ok = bool(found) == default
        elif kind == "num":
            ok = found is not None and float(found) == float(default)
        else:
            ok = found is not None and str(found) == str(default)
        if not ok:
            mismatched[name] = (default, found)
    assert mismatched == {}


@pytest.fixture(scope="module")
def build_module():
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "minimappr_build", ROOT / "minimappr" / "build.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_generated_index_is_in_sync_with_its_sources(build_module):
    # index.html is generated by minimappr/build.py and committed; a source
    # edit without a rebuild ships a page that ignores it.
    assert build_module.build() == INDEX.read_text(encoding="utf-8"), (
        "index.html is stale - run: python minimappr/build.py")


def test_every_data_block_the_app_reads_is_injected(build_module, app_js):
    # The app reads its embedded data back by element id; an id the build no
    # longer injects is a blank map, not a build error.
    read = set(re.findall(r'getElementById\("([\w-]+)"\)', app_js))
    injected = {tag_id for tag_id, _path in build_module.DATA}
    assert read == injected


def test_every_vendor_and_data_file_exists(build_module):
    base = ROOT / "minimappr"
    for rel in list(build_module.VENDOR) + [p for _i, p in build_module.DATA]:
        assert (base / rel).is_file(), rel


# ------------------------------------------------------- row overrides


def test_row_key_scheme_matches_the_python_side(app_js):
    # The two apps write the same project-shaped override keys, so the
    # separator and the tag names have to agree exactly.
    from pymappr.styling.legend import ROW_SEP

    separator = re.search(r'const ROW_SEP="([^"]*)"', app_js)
    assert separator, "ROW_SEP not found"
    assert separator.group(1).encode().decode("unicode_escape") == ROW_SEP

    tags = set(re.findall(r'rowKey\("(\w+)"', app_js))
    assert tags <= {"group", "color", "symbol", "pair"}, tags


def test_sources_carry_no_nul_bytes():
    # A literal NUL in a source file makes git treat it as binary and hides
    # every future diff; the separator must be written as an escape.
    for path in list(APP.glob("*.js")) + [BODY, INDEX]:
        assert b"\x00" not in path.read_bytes(), path.name


def test_override_helpers_exist_in_the_js(app_js):
    # These mirror pymappr.styling.styles.apply_override and friends; the
    # render path and the editor both depend on them.
    for name in ("applyOverride", "overrideLabel", "isHidden", "manualOrder",
                 "rowKey", "legendRowsFor", "moveRow", "setOverride"):
        assert f"function {name}(" in app_js, name


def test_manual_is_offered_as_an_order(body, app_js):
    # Reordering only takes effect under manual order, so the option has to
    # exist in the markup and the reorder has to switch to it.
    assert '<option value="manual">' in body
    assert 'opts.legOrder="manual"' in app_js


# ------------------------------------------------------- map controls


@pytest.fixture(scope="module")
def map_controls():
    """The MAP_CONTROLS table as [(id, kind, default), ...]."""
    source = STATE.read_text(encoding="utf-8")
    table = re.search(r"const MAP_CONTROLS = \[(.*?)\n\];", source, re.S)
    assert table, "MAP_CONTROLS table not found"
    rows = [(name, kind, _literal(default)) for name, kind, default in
            re.findall(r'\["(\w+)",\s*"(\w+)",\s*(.+?)\],', table.group(1))]
    assert rows, "MAP_CONTROLS parsed empty"
    return rows


def test_every_map_control_exists_with_its_default(map_controls, body):
    # The same contract as the legend table: a row whose control is missing
    # or starts at another value is a setting that silently misbehaves.
    mismatched = {}
    for name, kind, default in map_controls:
        found = _markup_default(body, name)
        if kind == "bool":
            ok = found is not None and bool(found) == default
        elif kind == "num":
            ok = found not in (None, "") and float(found) == float(default)
        else:
            ok = found is not None and str(found) == str(default)
        if not ok:
            mismatched[name] = (default, found)
    assert mismatched == {}


# -------------------------------------------- constants shared with PyMappr
#
# MiniMappr ports these from the Python side, and the two apps should draw
# the same map from the same settings, so each copy is checked against its
# source rather than trusted to stay in step.


def _js_value(app_js: str, name: str):
    """A JS constant's value: a number, a string, or a flat array of them."""
    match = re.search(r"\b%s\s*=\s*(\[[^\]]*\]|\"[^\"]*\"|[\d.]+)" % name,
                      app_js)
    assert match, f"{name} not found"
    text = match.group(1)
    if text.startswith("["):
        return [_literal(item) for item in text[1:-1].split(",")
                if item.strip()]
    return _literal(text)


def test_palettes_match_pymappr(app_js):
    from pymappr.styling import styles

    for name in ("DEFAULT_PALETTE", "OKABE_ITO", "BLACK_AND_WHITE"):
        assert _js_value(app_js, name) == getattr(styles, name), name


def test_point_outlines_match_pymappr(app_js):
    from pymappr.styling import styles

    assert _js_value(app_js, "POINT_EDGE_COLOR") == styles.POINT_EDGE_COLOR
    assert _js_value(app_js, "POINT_EDGE_WIDTH") == styles.POINT_EDGE_WIDTH
    assert (tuple(_js_value(app_js, "PUBLICATION_POINT_EDGE"))
            == tuple(styles.PUBLICATION_POINT_EDGE))


def test_shape_limit_matches_pymappr(app_js):
    from pymappr.styling.styles import LEGIBLE_MARKER_LIMIT

    assert _js_value(app_js, "LEGIBLE_MARKER_LIMIT") == LEGIBLE_MARKER_LIMIT


def test_scale_bar_maths_matches_pymappr(app_js):
    from pymappr.styling import decorations

    assert _js_value(app_js, "NICE_LENGTHS") == list(decorations._NICE)
    assert _js_value(app_js, "METRES_PER_MILE") == decorations.METRES_PER_MILE
    assert _js_value(app_js, "CORNERS") == decorations.CORNERS
    assert _js_value(app_js, "SCALE_WIDTH") == decorations.ScaleBarOptions().width


def test_coordinate_hints_match_pymappr(app_js):
    from pymappr.files import data_loader

    assert _js_value(app_js, "LON_HINTS") == list(data_loader._LON_HINTS)
    assert _js_value(app_js, "LAT_HINTS") == list(data_loader._LAT_HINTS)


def test_every_pymappr_projection_is_offered(app_js):
    from pymappr.geo.projections import PROJECTIONS

    table = re.search(r"const PROJ_DEFS = \{(.*?)\n\};", app_js, re.S)
    offered = set(re.findall(r'^\s*"([^"]+)":\{', table.group(1), re.M))
    assert set(PROJECTIONS) - offered == set()


def test_every_pymappr_grid_spacing_is_offered(body):
    # The control panel imports Tk, so its table is read as text.
    tables = ROOT / "pymappr" / "ui" / "control_panel" / "tables.py"
    source = tables.read_text(encoding="utf-8")
    # The labels hold "\N{DEGREE SIGN}", so the table ends at a brace that
    # closes a line, not at the first one.
    block = re.search(r"GRATICULE_CHOICES = \{(.*?)\}\n", source, re.S).group(1)
    pymappr = {float(v) for v in re.findall(r":\s*([\d.]+)", block)}
    offered = {float(v) for v in re.findall(r'data-grat="([\d.]+)"', body)}
    assert pymappr and pymappr <= offered


def test_publication_style_matches_pymappr(app_js):
    from pymappr.styling.legend import PUBLICATION_LEGEND, LegendOptions

    source = (ROOT / "pymappr" / "handlers" / "presets.py").read_text(
        encoding="utf-8")
    dpi = re.search(r'PUBLICATION_DPI = "(\d+)"', source).group(1)
    assert _js_value(app_js, "PUBLICATION_DPI") == float(dpi)

    table = re.search(r"const PUBLICATION_LEGEND = \{(.*?)\};", app_js, re.S)
    js = {key: _literal(value) for key, value in
          re.findall(r"(\w+):([^,}\s]+)", table.group(1))}
    same = {"frame": "legFrame", "frame_color": "legFrameColor",
            "frame_alpha": "legFrameAlpha", "frame_edge_color": "legFrameEdge",
            "frame_width": "legFrameWidth", "shadow": "legShadow",
            "label_italic": "legLabelItalic"}
    for field, key in same.items():
        assert js[key] == PUBLICATION_LEGEND[field], field
    # Square corners: PyMappr has a switch, MiniMappr a radius.
    assert PUBLICATION_LEGEND["rounded"] is False and js["legRadius"] == 0
    # Sizes are points there and pixels here, so what carries over is the
    # step up from each app's own defaults.
    defaults = LegendOptions()
    controls = dict((n, d) for n, _k, d in re.findall(
        r'\["(\w+)",\s*"(\w+)",\s*([\d.]+)\]', app_js))
    for field, key in (("fontsize", "legFont"),
                       ("title_fontsize", "legTitleFont")):
        step = PUBLICATION_LEGEND[field] - getattr(defaults, field)
        assert js[key] - float(controls[key]) == step, field


# ------------------------------------------------------------ inset map
#
# The inset is ported from renderer/inset.py and geo/regions.py; its look,
# its limits and its defaults are checked against them like the rest.


def test_inset_look_matches_pymappr(app_js):
    from pymappr.renderer import tables

    for name in ("INSET_LAND", "INSET_LINE_SCALE", "INSET_POINT_SCALE",
                 "INSET_FRAME_WIDTH", "INSET_BOX_WIDTH"):
        assert _js_value(app_js, name) == getattr(tables, name), name


def test_inset_layout_matches_pymappr(app_js):
    from pymappr.geo import regions
    from pymappr.renderer import inset

    pairs = {"INSET_PAD": inset._PAD, "INSET_GAP": inset._GAP,
             "INSET_SIZE_RANGE": list(inset._SIZE_RANGE),
             "INSET_MAX_HEIGHT": inset._MAX_HEIGHT,
             "INSET_GLOBE_MARGIN": inset._GLOBE_MARGIN,
             "INSET_EDGE_POINTS": inset._EDGE_POINTS,
             "REGION_PAD": regions._PAD, "REGION_NEARBY": regions._NEARBY,
             "REGION_NEARBY_MIN": regions._NEARBY_MIN}
    for name, value in pairs.items():
        assert _js_value(app_js, name) == value, name


def test_inset_defaults_match_pymappr(map_controls):
    from pymappr.styling.decorations import InsetOptions

    defaults = InsetOptions()
    controls = {name: default for name, _kind, default in map_controls}
    same = {"show": "insetShow", "position": "insetPos", "size": "insetSize",
            "zoom_out": "insetZoomOut", "projection": "insetProjection",
            "countries": "insetCountries", "land": "insetLand",
            "ocean": "insetOcean", "points": "insetPoints", "box": "insetBox",
            "box_color": "insetBoxColor"}
    for field, key in same.items():
        assert controls[key] == getattr(defaults, field), field
    # PyMappr starts on "state", which needs admin-1 outlines MiniMappr does
    # not carry; the next region down is the default here.
    assert defaults.region == "state" and controls["insetRegion"] == "country"


def _select_values(body: str, element_id: str) -> list[str]:
    select = re.search(r'<select[^>]*id="%s".*?</select>' % element_id,
                       body, re.S)
    assert select, element_id
    return re.findall(r'<option value="([^"]*)"', select.group(0))


def test_inset_choices_match_pymappr(body, app_js):
    from pymappr.geo.layers import CONTINENT_EXTENTS
    from pymappr.styling import decorations

    assert _select_values(body, "insetProjection") == decorations.INSET_PROJECTIONS
    assert _select_values(body, "insetOcean") == decorations.INSET_OCEANS
    assert _js_value(app_js, "INSET_PROJECTIONS") == decorations.INSET_PROJECTIONS
    assert _js_value(app_js, "INSET_OCEANS") == decorations.INSET_OCEANS
    assert set(_select_values(body, "insetPos")) == set(decorations.CORNERS)
    regions = [r for r in decorations.INSET_REGIONS if r != "state"]
    assert set(_select_values(body, "insetRegion")) == (
        set(regions) | set(CONTINENT_EXTENTS))


def test_continent_extents_match_pymappr(app_js):
    # The inset's continent regions and the map's own extents both use them.
    from pymappr.geo.layers import CONTINENT_EXTENTS

    table = re.search(r"const CONTINENT_EXTENTS = \{(.*?)\};", app_js, re.S)
    js = {name: [float(v) for v in values.split(",")] for name, values in
          re.findall(r'"([^"]+)":\[([^\]]*)\]', table.group(1))}
    assert js == {name: list(ext) for name, ext in CONTINENT_EXTENTS.items()}
