"""Checks on the MiniMappr front end.

There is no JavaScript engine in this project, so these do not run the app.
What they do cover is the contract that is easiest to break by hand: a
legend setting is declared once in ``LEGEND_CONTROLS`` and has to line up
with a control in the markup, with the code that reads it, and with the
generated ``index.html``. A mismatch there is silent in the browser - the
control simply does nothing - so it is worth catching here.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
APP = ROOT / "minimappr" / "app"
BODY = ROOT / "minimappr" / "body.html"
STATE = APP / "30-styles-state.js"
INDEX = ROOT / "index.html"

_JS_LITERALS = {"true": True, "false": False, "null": None}


def _literal(text: str):
    text = text.strip()
    if text in _JS_LITERALS:
        return _JS_LITERALS[text]
    if text.startswith('"'):
        return text.strip('"')
    return float(text)


@pytest.fixture(scope="module")
def controls():
    """The LEGEND_CONTROLS table as [(id, kind, default), ...]."""
    source = STATE.read_text(encoding="utf-8")
    table = re.search(r"const LEGEND_CONTROLS = \[(.*?)\n\];", source, re.S)
    assert table, "LEGEND_CONTROLS table not found"
    rows = [(name, kind, _literal(default)) for name, kind, default in
            re.findall(r'\["(\w+)",\s*"(\w+)",\s*(.+?)\],', table.group(1))]
    assert rows, "LEGEND_CONTROLS parsed empty"
    return rows


@pytest.fixture(scope="module")
def body():
    return BODY.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def app_js():
    return "".join(p.read_text(encoding="utf-8")
                   for p in sorted(APP.glob("*.js")))


def _markup_default(body: str, element_id: str):
    """A control's default straight out of the markup."""
    select = re.search(r'<select[^>]*id="%s".*?</select>' % element_id,
                       body, re.S)
    if select:
        option = re.search(r'<option value="([^"]*)"', select.group(0))
        return option.group(1) if option else None
    tag = re.search(r'<input[^>]*id="%s"[^>]*>' % element_id, body)
    if not tag:
        return None
    if 'type="checkbox"' in tag.group(0):
        return "checked" in tag.group(0)
    value = re.search(r'value="([^"]*)"', tag.group(0))
    return value.group(1) if value else ""


def test_every_declared_control_exists_in_the_markup(controls, body):
    declared = {name for name, _kind, _default in controls}
    in_markup = set(re.findall(r'id="(leg\w+)"', body))
    assert declared - in_markup == set(), "declared but no control on the page"
    assert in_markup - declared == set(), "control on the page but undeclared"


def test_no_option_is_read_without_being_declared(controls, app_js):
    declared = {name for name, _kind, _default in controls}
    read = set(re.findall(r"opts\.(leg\w+)", app_js))
    assert read - declared == set(), "read from opts but never declared"


def test_no_option_is_declared_without_being_used(controls, app_js):
    # A declared-but-unread setting is a control that visibly does nothing.
    declared = {name for name, _kind, _default in controls}
    read = set(re.findall(r"opts\.(leg\w+)", app_js))
    assert declared - read == set(), "declared but nothing reads it"


def test_markup_defaults_match_the_table(controls, body):
    mismatched = {}
    for name, kind, default in controls:
        found = _markup_default(body, name)
        if kind == "bool":
            ok = bool(found) == default
        elif kind == "num":
            ok = found is not None and float(found) == float(default)
        else:
            ok = found is not None and str(found) == str(default)
        if not ok:
            mismatched[name] = (default, found)
    assert mismatched == {}


def test_generated_index_is_in_sync_with_its_sources():
    # index.html is generated by minimappr/build.py and committed; a source
    # edit without a rebuild ships a page that ignores it.
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "minimappr_build", ROOT / "minimappr" / "build.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    assert module.build() == INDEX.read_text(encoding="utf-8"), (
        "index.html is stale - run: python minimappr/build.py")
