"""The Python script: its header and configuration block, and the files a
Python working directory export adds."""

from __future__ import annotations

from pymappr.export.config import _style_dict
from pymappr.export.literals import (REPO_URL, _comment_text, _py,
                                     _safe_name, _template, _wrapped_items)


def _py_docstring_text(text: str) -> str:
    """*text* escaped for a normal (non-raw) docstring, where a backslash
    starts an escape: "Field\\Notes" would otherwise read as a malformed
    \\N{...} escape and stop the script compiling."""
    return text.replace("\\", "\\\\")


def _py_header(config: dict) -> str:
    notes = "".join(f"\n#   - {note}" for note in config["notes"])
    if notes:
        notes = ("\n# Shown in PyMappr but NOT reproduced by this script:"
                 + notes)
    if config["data_mode"] == "files":
        data_note = ("Your point data is in the data/ folder as CSV - edit "
                     "or replace those files\nto update the map.")
    else:
        data_note = ("Your point data is embedded below in DATASETS, so "
                     "this single file is\nself-contained - nothing else "
                     "to download or keep alongside it.")
    return f'''\
#!/usr/bin/env python3
# Made with {config["generator"]} - {REPO_URL}
"""Recreate the PyMappr map "{_py_docstring_text(_safe_name(config["project"]))}" outside PyMappr.

Generated by {config["generator"]} from pre-made function templates and
the map's saved settings

Just run it: open this file in an IDE (PyCharm, VS Code, ...) and click
Run, or `python recreate_map.py` in a terminal. If a package it needs
(pandas, geopandas, matplotlib) is missing, it prints the pip command to
install it - or run `python recreate_map.py --install-deps` to have it
installed for you. The map data is downloaded from Natural Earth and cached
in naturalearth_cache/ next to this script.

Output:  map.png (also opens an interactive window).

{data_note}
"""
# Projection: {config["projection"]}{notes}
'''


def _py_layer_entry(layer: dict) -> dict:
    entry = {"name": layer["name"], "category": layer["category"],
             "scale": layer["scale"], "kind": layer["kind"],
             "z": round(layer["z"], 6), "color": layer["color"]}
    if layer.get("member"):
        entry["member"] = layer["member"]
    if layer.get("filter"):
        entry["filter"] = layer["filter"]
    if layer["kind"] == "fill":
        entry.update(edgecolor=layer["edgecolor"],
                     width=round(layer["width"], 3), alpha=layer["alpha"])
    elif layer["kind"] in ("line", "continents"):
        entry.update(width=round(layer["width"], 3),
                     linestyle=layer["linestyle"])
    else:
        entry.update(marker=layer["marker"], size=layer["size"],
                     edgecolor=layer["edgecolor"])
        if layer.get("min_zoom_max") is not None:
            entry["min_zoom_max"] = layer["min_zoom_max"]
    return entry


def _py_config(config: dict) -> str:
    lines = ["", "# ------------------------- map configuration (from "
                 "PyMappr) -------------------------", ""]
    lines.append(f'MAP_CRS = {_py(config["crs"])}'
                 "  # proj4 string, or None for plain lon/lat degrees")
    proj = config["proj"]
    lines.append(f"PROJ = {{'bounds': {_py(proj['bounds'])}, "
                 f"'max_lat': {_py(proj['max_lat'])}, "
                 f"'min_lat': {_py(proj['min_lat'])}, "
                 f"'lon_0': {_py(proj['lon_0'])}, "
                 f"'lon_halfspan': {_py(proj['lon_halfspan'])}, "
                 f"'hemisphere': {_py(proj['hemisphere'])}}}")
    lines.append(f'CLIP_CAP = {_py(config["clip_cap"])}'
                 "  # (lon0, lat0, radius) visible cap for the globe, "
                 "else None")
    lines.append(f'VIEW = {_py(config["view"])}'
                 "  # axis limits in map coordinates (x0, x1, y0, y1)")
    lines.append(f'ZOOM = {_py(config["zoom"])}'
                 "  # log2(world width / view width), used for culling")
    lines.append(f'FIGSIZE = {_py(config["figsize"])}'
                 "  # inches; the app canvas geometry")
    lines.append(f'MARGINS = {_py(config["margins"])}'
                 "  # axes box as figure fractions (l, b, r, t)")
    lines.append(f'BASEMAP = {_py(config["basemap"])}'
                 "  # raster basemap mode (\"simple\" = none)")
    grat = config["graticule"]
    lines.append(f"GRATICULE = {{'interval': {_py(grat['interval'])}, "
                 f"'labels': {_py(grat['labels'])}}}")
    compass = dict(config["compass_options"])
    compass["show"] = config["compass"]
    lines.append(f'COMPASS = {_py(compass)}')
    lines.append(f'SCALE_BAR = {_py(config["scale_bar"])}')
    lines.append(f'POINT_ALPHA = {_py(config["point_alpha"])}')
    lines.append(f'POINT_EDGE = {_py(config["point_edge"])}'
                 "  # outline around filled markers")
    lines.append(f'DPI = {_py(config["dpi"])}')
    lines.append('OUTPUT_FILE = "map.png"')
    lines.append("")
    lines.append("# Natural Earth layers enabled in PyMappr, with the "
                 "renderer's true draw")
    lines.append("# order (z). A filter is (column, kept values, keep?) "
                 "applied after download.")
    lines.append("LAYERS = [")
    for layer in config["layers"]:
        entry = _py_layer_entry(layer)
        body = ", ".join(f"{_py(k)}: {_py(v)}" for k, v in entry.items())
        lines.append(f"    # PyMappr layer: {layer['key']}")
        lines.append(f"    {{{body}}},")
    lines.append("]")
    lines.append("")
    lines.append("# Map label layers (country/city/... names), like the "
                 "app draws them.")
    lines.append("LABEL_LAYERS = [")
    for spec in config["label_layers"]:
        body = ", ".join(f"{_py(k)}: {_py(v)}" for k, v in spec.items())
        lines.append(f"    {{{body}}},")
    lines.append("]")
    lines.append("")
    lines.append("# One entry per dataset. lon_col/lat_col name the "
                 "coordinate columns")
    lines.append("# (None = auto-detect by column name).")
    lines.append("# label_map renames groups for the legend; 'styles' maps "
                 "each group to its")
    lines.append("# point style, in render order (open = outline-only "
                 "marker).")
    lines.append("DATASETS = [")
    for spec in config["datasets"]:
        if spec.get("source"):
            lines.append("    # originally imported from: "
                         + _comment_text(spec["source"]))
        lines.append("    {")
        for key in ("name", "path", "inline_data", "lon_col", "lat_col",
                    "group_col", "color_col", "symbol_col",
                    "default_label", "label_map", "open_col",
                    "open_values"):
            lines.append(f"        {_py(key)}: {_py(spec[key])},")
        lines.append("        'styles': {")
        for value, style in spec["styles"].items():
            lines.append(f"            {_py(value)}: "
                         f"{_py(_style_dict(style))},")
        lines.append("        },")
        lines.append("    },")
    lines.append("]")
    lines.append("")
    sections = config["legend_sections"]
    if sections is None:
        lines.append("LEGEND_SECTIONS = None"
                     "  # plain legend: one row per style, in DATASETS")
    else:
        lines.append("# Sectioned legend, like the app's: (label, style, "
                     "depth) rows, where")
        lines.append("# depth indents a row under the one above it (a "
                     "nested genus/species key).")
        lines.append("LEGEND_SECTIONS = [")
        for title, entries in sections:
            lines.append(f"    ({_py(title)}, [")
            for label, style, *rest in entries:
                depth = rest[0] if rest else 0
                fields = _style_dict(style)
                if fields is None:
                    drawn = "None"
                else:
                    drawn = "{" + ", ".join(f"{_py(k)}: {_py(v)}"
                                            for k, v in fields.items()) + "}"
                lines.append(
                    f"        ({_py(label)}, {drawn}, {depth}),")
            lines.append("    ]),")
        lines.append("]")
    lines.append("")
    rows = config.get("legend_rows")
    lines.append("# Legend rows for the plain legend, in order (None = "
                 "every style, in DATASETS order).")
    lines.append(f"LEGEND_ROWS = {_py(rows)}")
    lines.append("")
    note = config.get("open_note")
    lines.append("# The legend's last row: what the open symbols mark "
                 "(None = no open symbols).")
    if note is None:
        lines.append("OPEN_NOTE = None")
    else:
        lines.append(f"OPEN_NOTE = ({_py(note[0])}, "
                     f"{_py(_style_dict(note[1]))})")
    lines.append("")
    legend = config["legend"]
    body = ", ".join(f"{_py(k)}: {_py(v)}" for k, v in legend.items())
    lines.append(f"LEGEND = {{{body}}}")
    lines.append("")
    lines += _py_inset(config.get("inset"))
    return "\n".join(lines) + "\n"


def _py_inset(inset: dict | None) -> list[str]:
    lines = ["# The inset map, as PyMappr drew it (None = no inset): rect is "
             "its place in the",
             "# map's axes fraction (x, y, width, height), limits its axis "
             "limits in its own",
             "# CRS (None = plain lon/lat), clip_cap / band what layers are "
             "clipped to before",
             "# reprojecting, and box the outline linking the two maps, "
             "drawn on the inset",
             "# or on the main map (None in x/y breaks the line)."]
    if inset is None:
        return lines + ["INSET = None"]
    lines.append("INSET = {")
    for key in ("projection", "crs", "rect", "lon_0", "lat_0", "min_lat",
                "max_lat", "lon_halfspan", "hemisphere", "clip_cap", "band",
                "limits", "zoom", "points", "point_scale", "frame_width",
                "clear"):
        lines.append(f"    {_py(key)}: {_py(inset[key])},")
    lines.append("    'layers': [")
    for layer in inset["layers"]:
        entry = _py_layer_entry(layer)
        body = ", ".join(f"{_py(k)}: {_py(v)}" for k, v in entry.items())
        lines.append(f"        # PyMappr inset layer: {layer['key']}")
        lines.append(f"        {{{body}}},")
    lines.append("    ],")
    horizon = inset["horizon"]
    if horizon is None:
        lines.append("    'horizon': None,")
    else:
        lines.append("    # The globe's horizon (x list, y list).")
        lines.append("    'horizon': (")
        for values in horizon:
            lines.append("        [")
            lines += _wrapped_items([_py(v) for v in values], " " * 12)
            lines.append("        ],")
        lines.append("    ),")
    box = inset["box"]
    if box is None:
        lines.append("    'box': None,")
    else:
        lines.append(f"    'box': {{'target': {_py(box['target'])}, "
                     f"'color': {_py(box['color'])}, "
                     f"'width': {_py(box['width'])},")
        for axis in ("x", "y"):
            lines.append(f"            {_py(axis)}: [")
            lines += _wrapped_items([_py(v) for v in box[axis]], " " * 16)
            lines.append("            ],")
        lines.append("    },")
    lines.append("}")
    return lines


def _python_script(config: dict) -> str:
    return (_py_header(config) + _py_config(config)
            + _template("recreate_map.py"))


# -------------------------------------------------- working directory export

_PY_REQUIREMENTS = ("geopandas>=1.0\n"
                    "matplotlib>=3.8\n"
                    "numpy>=1.26\n"
                    "pandas>=2.1\n")

_PY_GITIGNORE = "naturalearth_cache/\nmap.png\n__pycache__/\n"


def _py_readme(project: str) -> str:
    return f'''# {project} - PyMappr map export

A ready-to-run Python recreation of the PyMappr map "{project}"
(pandas + geopandas + matplotlib), replicating PyMappr's own renderer.

## Run it

Open this folder in your IDE (PyCharm, VS Code, ...) and run
`recreate_map.py`. Or, from a terminal in this folder:

    python recreate_map.py

If a package is missing the script tells you; set up the environment
with:

    pip install -r requirements.txt

(or run `python recreate_map.py --install-deps` to let it install them).

It downloads its map data from Natural Earth into
`naturalearth_cache/` and reads your point data from the CSV files in
`data/`. The finished map is written to `map.png`.
'''
